name: Daily Financials Update Workflow

on:
  schedule:
    # UTC 15:10 → KST 다음날 00:10
    - cron: '10 15 * * *'
  workflow_dispatch:

jobs:
  run:
    # self-hosted Windows x64 러너 지정
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bypass PowerShell Execution Policy
        # PowerShell에서 스크립트 실행 막아두었지만, 이 GitHub Actions 실행 동안에는 풀어주세요!
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell

      - name: Set UTF-8 encoding for console
        run: chcp 65001
        shell: cmd

      - name: Set PYTHONIOENCODING=utf-8 for all steps
        run: echo "PYTHONIOENCODING=utf-8" >> $env:GITHUB_ENV
        shell: powershell
        
      - name: Check Python version (미리 설치된 기존 Python 사용)
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collector
        run: python main.py
        env:
          DART_API_KEY:   ${{ secrets.DART_API_KEY }}
          DATABASE_URL:   ${{ secrets.DATABASE_URL }}

      - name: Run internal DB work
        run: python scripts/do_db_work.py
        env:
          DATABASE_URL:   ${{ secrets.DATABASE_URL }}

      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address:  smtp.gmail.com
          server_port:     465
          username:        ${{ secrets.GMAIL_USER }}
          password:        ${{ secrets.GMAIL_APP_PASSWORD }}
          subject:         'Daily Financials Update Completed'
          body:            '✅ 재무정보 업데이트 및 DB 업로드가 완료되었습니다.'
          to:              hmroh7363@gmail.com
