name: Daily Financials Update Workflow

on:
  schedule:
    - cron: "0 15 * * *"  # 한국 시간 매일 0시 (UTC 15시)
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collector
        run: python update_financials.py
        env:
          DART_API_KEY: ${{ secrets.DART_API_KEY }}
          NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
