name: Daily Financials Update Workflow

on:
  schedule:
    # UTC 15:10 → KST 다음날 00:10
    - cron: '10 15 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted  # Windows X64 self-hosted 러너

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collector (재무제표 수집)
        id: run-main
        shell: powershell
        continue-on-error: true
        env:
          DART_API_KEY:   ${{ secrets.DART_API_KEY }}
          DATABASE_URL:   ${{ secrets.DATABASE_URL }}
        run: |
         # 1) 콘솔을 UTF-8 모드로 전환
         chcp.com 65001
         [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

          # 2) PowerShell 에러 무시
          $ErrorActionPreference = 'Continue'
      
          # 3) 파이썬 실행 결과 캡처
          $output = python main.py 2>&1
          Write-Host $output

      - name: Send notification email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          from:     ${{ secrets.GMAIL_USER }}
          to:       hmroh7363@gmail.com
          subject: >
            ${{ job.status == 'failure' && '❌ 재무정보 업데이트 실패'
               || '✅ 재무정보 업데이트 완료' }}
          body: >
            ${{ job.status == 'failure'
                && '예기치 못한 오류로 재무정보 수집이 실패했습니다.'
                || '정상적으로 재무정보 수집 및 DB 업로드가 완료되었습니다.' }}
