name: Daily Financials Update Workflow

on:
  schedule:
    # UTC 15:10 → KST 다음날 00:10
    - cron: '10 15 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v3

      - name: Bypass PowerShell Execution Policy
        shell: powershell
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

      - name: Set UTF-8 encoding for console (cmd)
        shell: cmd
        run: chcp 65001

      - name: Set PYTHONIOENCODING=utf-8 for all steps
        shell: powershell
        run: echo "PYTHONIOENCODING=utf-8" >> $env:GITHUB_ENV

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collector (재무제표 수집)
        id: run-main
        shell: powershell
        env:
          …
        run: |
          $output = python main.py 2>&1
          Write-Host $output

          if ($LASTEXITCODE -ne 0) {
            if ($output -match 'DART API 일일 호출 한도\(19000\)') {
              echo "stopped_reason=19000" >> $env:GITHUB_OUTPUT
              exit 0
            }
            exit $LASTEXITCODE
          }
          
      - name: Send notification email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username:    ${{ secrets.GMAIL_USER }}
          password:    ${{ secrets.GMAIL_APP_PASSWORD }}
          from:        ${{ secrets.GMAIL_USER }}
          to:          hmroh7363@gmail.com
          subject: >
            ${{ steps.check19000.outputs.stopped_reason == '19000'
                && '⛔ DART 호출 제한으로 중단됨'
                || job.status == 'failure'
                && '❌ 재무정보 업데이트 실패'
                || '✅ 재무정보 업데이트 완료' }}
          body: >
            ${{ steps.check19000.outputs.stopped_reason == '19000'
                && 'DART API 호출 횟수(19000)에 도달하여 수집을 중단했습니다.'
                || job.status == 'failure'
                && '예기치 못한 오류로 재무정보 수집이 실패했습니다.'
                || '정상적으로 재무정보 수집 및 DB 업로드가 완료되었습니다.' }}
